### ISSUE TITLE
Not an issue, but question for you

### ISSUE THREAD

**Issue by ruckc** [pmarasse/adtokengroups#1]
I see all of your code to convert a tokenGroup string into the Group DN.  I am in the process of converting from CAS 3.6 to CAS 5.3.  How do you get Ldaptive, or any Java LDAP API to return the tokenGroups attribute?  When I try to use CAS's built-in LdapAuthenticationHandler it crashes due to LDAP: error code 1, which seems to only crash when tokenGroups is requested without the Scope being set to BASE.

I'm trying to use raw LDAP Queries to get tokenGroups to return.  With ldapsearch I can do it, if I exclude the filter.  I can't find any Java LDAP SDK's that don't crash with a NullPointerException or javax.naming.directory.InvalidSearchFilterException.

Can you give me any pointers?  You are the only person i've found on github that is using tokenGroups in Java.

**Comment by pmarasse** [comment]
You're also working about moving from CAS 3.x to 5.3, great !

As far as I know, CAS's LdapAuthenticationHandler has no way to handle binary LDAP attribute.

With Ldaptive, you need to request "tokenGroups;binary" to retrieve the binary value of an attribute, and use SearchRequest.setBinaryAttributes (without ";binary" suffix) *and* SearchRequest.setReturnAttributes (with ";binary" suffix) to get it. See [this project](https://dev.ch-poitiers.fr/mssante/mssante-listeblanche/blob/master/src/main/java/fr/chpoitiers/mssante/whitelist/processors/MXFingerprintsFetchByLdapAndProcess.java#L263) where I get userCertificate from a LDAP directory with Ldaptive.

Another issue with AD : as tokenGroups is a constructed attribute, You have to fetch it with BASE scope [see this comment](https://github.com/pmarasse/cas-persondir-ldap/blob/1b5a0376bf8a3dfbb2d3bd4c2fd4b9b67379f8e8/src/main/java/net/archigny/cas/persondir/ldap/LdapPersonAttributeDao.java#L99) on my other project.

I my organization, we're moving slowly to CAS 5.3, so I'll have to update these components soon.

**Comment by ruckc** [comment]
Thanks for the pointers.  I was trying the BASE scope, but all the queries fail before getting to LDAP as they seem to all require an actual searchFilter, and when i pass (objectclass=*) I get an ldap error 1.  Maybe I have to do the binary thing.

Thanks for the help!
